### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by lb5tr** [lb5tr/burger-bot#2]
- [ ] refactor (in progress) - use decorators for command handlers, reduce duplication, major gateway refactor
- [ ] authentication and buffered output module
- [ ] error handling / auto reconnect
- [ ] move every module to separate directory
- [ ] `ModuleFactory`
